name: Terraform

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/preprod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login \
            --service-principal \
            --username "bb8e14ee-f53f-4665-8ddd-550c824843e7" \
            --password "28bab2c9-dbe6-4f1a-821f-4b773dc6812c" \
            --tenant "8b244074-9819-4f7f-835d-3cf7a518454f"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "76810c64-6731-42a9-98ae-4a8c5ba8fb64"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    needs: terraform-plan

    # Apply ONLY after push to main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: environments/preprod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login \
            --service-principal \
            --username "bb8e14ee-f53f-4665-8ddd-550c824843e7" \
            --password "28bab2c9-dbe6-4f1a-821f-4b773dc6812c" \
            --tenant "8b244074-9819-4f7f-835d-3cf7a518454f"

      - name: Set Azure Subscription
        run: |
          az account set \
            --subscription "76810c64-6731-42a9-98ae-4a8c5ba8fb64"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
